export const adminSeed = {
  name: "Admin",
  username: "admin",
  password: "admin123",
  role: "admin",
};

export const productSeed = [
  {
    legacyId: "1",
    name: "Chrome Basin Faucet",
    description:
      "Modern single-handle basin faucet with chrome finish. Featuring ceramic disc cartridge for drip-free performance.",
    price: 89.99,
    category: "Faucets",
    brand: "AquaFlow",
    image:
      "https://images.unsplash.com/photo-1595428774862-a79ab68dbabb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBiYXRocm9vbSUyMGZhdWNldCUyMHRhcHxlbnwxfHx8fDE3NzMwNDg1NzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 45,
    rating: 4.5,
    reviews: 128,
  },
  {
    legacyId: "2",
    name: "Waterfall Bath Faucet",
    description:
      "Contemporary waterfall bath faucet with brushed nickel finish. Wall-mounted design for modern bathrooms.",
    price: 149.99,
    category: "Faucets",
    brand: "LuxeBath",
    image:
      "https://images.unsplash.com/photo-1595428774862-a79ab68dbabb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBiYXRocm9vbSUyMGZhdWNldCUyMHRhcHxlbnwxfHx8fDE3NzMwNDg1NzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 23,
    rating: 4.8,
    reviews: 89,
  },
  {
    legacyId: "3",
    name: "Kitchen Mixer Tap",
    description:
      "Pull-down kitchen faucet with dual spray modes. Stainless steel construction with easy-clean nozzle.",
    price: 129.99,
    category: "Faucets",
    brand: "AquaFlow",
    image:
      "https://images.unsplash.com/photo-1595428774862-a79ab68dbabb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBiYXRocm9vbSUyMGZhdWNldCUyMHRhcHxlbnwxfHx8fDE3NzMwNDg1NzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 31,
    rating: 4.6,
    reviews: 156,
  },
  {
    legacyId: "4",
    name: "Modern Wall-Hung Toilet",
    description:
      "Space-saving wall-hung toilet with soft-close seat. Dual-flush system for water conservation.",
    price: 399.99,
    category: "Toilets",
    brand: "SaniPro",
    image:
      "https://images.unsplash.com/photo-1595514535316-b8c85bf9bbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMGNlcmFtaWMlMjB0b2lsZXQlMjBiYXRocm9vbXxlbnwxfHx8fDE3NzMwNDg1NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 18,
    rating: 4.7,
    reviews: 92,
  },
  {
    legacyId: "5",
    name: "Close Coupled Toilet",
    description:
      "Traditional close coupled toilet with rimless design. Easy to clean with powerful flush system.",
    price: 249.99,
    category: "Toilets",
    brand: "SaniPro",
    image:
      "https://images.unsplash.com/photo-1595514535316-b8c85bf9bbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMGNlcmFtaWMlMjB0b2lsZXQlMjBiYXRocm9vbXxlbnwxfHx8fDE3NzMwNDg1NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 27,
    rating: 4.4,
    reviews: 74,
  },
  {
    legacyId: "6",
    name: "Smart Toilet",
    description:
      "High-tech smart toilet with bidet function, heated seat, and automatic lid. Remote control included.",
    price: 899.99,
    category: "Toilets",
    brand: "TechSani",
    image:
      "https://images.unsplash.com/photo-1595514535316-b8c85bf9bbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMGNlcmFtaWMlMjB0b2lsZXQlMjBiYXRocm9vbXxlbnwxfHx8fDE3NzMwNDg1NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 8,
    rating: 4.9,
    reviews: 45,
  },
  {
    legacyId: "7",
    name: "Ceramic Countertop Basin",
    description:
      "Round countertop basin with smooth ceramic finish. Modern design perfect for contemporary bathrooms.",
    price: 159.99,
    category: "Basins",
    brand: "CeraStyle",
    image:
      "https://images.unsplash.com/photo-1659455299116-af958bd906ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXRocm9vbSUyMGJhc2luJTIwc2lua3xlbnwxfHx8fDE3NzMwNDg1NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 34,
    rating: 4.6,
    reviews: 112,
  },
  {
    legacyId: "8",
    name: "Undermount Sink",
    description:
      "Rectangular undermount bathroom sink. Overflow drain and pre-drilled faucet hole included.",
    price: 119.99,
    category: "Basins",
    brand: "CeraStyle",
    image:
      "https://images.unsplash.com/photo-1659455299116-af958bd906ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXRocm9vbSUyMGJhc2luJTIwc2lua3xlbnwxfHx8fDE3NzMwNDg1NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 41,
    rating: 4.3,
    reviews: 87,
  },
  {
    legacyId: "9",
    name: "Pedestal Basin",
    description:
      "Classic pedestal basin with traditional styling. Complete with pedestal base and fixings.",
    price: 189.99,
    category: "Basins",
    brand: "Heritage",
    image:
      "https://images.unsplash.com/photo-1659455299116-af958bd906ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXRocm9vbSUyMGJhc2luJTIwc2lua3xlbnwxfHx8fDE3NzMwNDg1NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 19,
    rating: 4.5,
    reviews: 63,
  },
  {
    legacyId: "10",
    name: "Rainfall Shower Head",
    description:
      "Large 12-inch square rainfall shower head. Chrome finish with anti-limescale nozzles.",
    price: 179.99,
    category: "Showers",
    brand: "RainDrop",
    image:
      "https://images.unsplash.com/photo-1677454759826-3922020f2ffb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaG93ZXIlMjBoZWFkJTIwYmF0aHJvb218ZW58MXx8fHwxNzczMDQ1NjgyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 52,
    rating: 4.7,
    reviews: 198,
  },
  {
    legacyId: "11",
    name: "Thermostatic Shower System",
    description:
      "Complete thermostatic shower system with overhead and handheld shower. Temperature control technology.",
    price: 449.99,
    category: "Showers",
    brand: "ThermoFlow",
    image:
      "https://images.unsplash.com/photo-1677454759826-3922020f2ffb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaG93ZXIlMjBoZWFkJTIwYmF0aHJvb218ZW58MXx8fHwxNzczMDQ1NjgyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 16,
    rating: 4.8,
    reviews: 134,
  },
  {
    legacyId: "12",
    name: "Shower Enclosure",
    description:
      "Frameless glass shower enclosure. 8mm toughened glass with chrome fittings. 900x900mm.",
    price: 599.99,
    category: "Showers",
    brand: "GlassLux",
    image:
      "https://images.unsplash.com/photo-1677454759826-3922020f2ffb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaG93ZXIlMjBoZWFkJTIwYmF0aHJvb218ZW58MXx8fHwxNzczMDQ1NjgyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 12,
    rating: 4.6,
    reviews: 71,
  },
  {
    legacyId: "13",
    name: "Towel Rail Set",
    description:
      "Chrome towel rail set including towel ring, rail, and toilet roll holder. Contemporary design.",
    price: 79.99,
    category: "Accessories",
    brand: "AccessPro",
    image:
      "https://images.unsplash.com/photo-1766727923661-35e86cf71b46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXRocm9vbSUyMGFjY2Vzc29yaWVzJTIwdG93ZWx8ZW58MXx8fHwxNzczMDQ1NjgzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 67,
    rating: 4.4,
    reviews: 203,
  },
  {
    legacyId: "14",
    name: "Bathroom Mirror Cabinet",
    description:
      "LED illuminated mirror cabinet with demister pad. Soft-close doors and internal shelving.",
    price: 229.99,
    category: "Accessories",
    brand: "MirrorTech",
    image:
      "https://images.unsplash.com/photo-1766727923661-35e86cf71b46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXRocm9vbSUyMGFjY2Vzc29yaWVzJTIwdG93ZWx8ZW58MXx8fHwxNzczMDQ1NjgzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 25,
    rating: 4.7,
    reviews: 98,
  },
  {
    legacyId: "15",
    name: "Soap Dispenser & Holder",
    description:
      "Wall-mounted soap dispenser and toothbrush holder set. Brushed stainless steel finish.",
    price: 49.99,
    category: "Accessories",
    brand: "AccessPro",
    image:
      "https://images.unsplash.com/photo-1766727923661-35e86cf71b46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXRocm9vbSUyMGFjY2Vzc29yaWVzJTIwdG93ZWx8ZW58MXx8fHwxNzczMDQ1NjgzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    inStock: true,
    quantity: 89,
    rating: 4.2,
    reviews: 167,
  },
];

export const customerSeed = [
  {
    name: "John Smith",
    email: "john@example.com",
    phone: "(555) 123-4567",
    address: "123 Main St, New York, NY 10001",
    totalOrders: 12,
    totalSpent: 2345.67,
    joinedAt: "2025-01-15",
  },
  {
    name: "Sarah Johnson",
    email: "sarah@example.com",
    phone: "(555) 234-5678",
    address: "456 Oak Ave, Brooklyn, NY 11201",
    totalOrders: 8,
    totalSpent: 1876.43,
    joinedAt: "2025-02-20",
  },
  {
    name: "Mike Brown",
    email: "mike@example.com",
    phone: "(555) 345-6789",
    address: "789 Pine Rd, Queens, NY 11354",
    totalOrders: 5,
    totalSpent: 987.25,
    joinedAt: "2025-03-01",
  },
  {
    name: "Emily Davis",
    email: "emily@example.com",
    phone: "(555) 456-7890",
    address: "321 Elm St, Manhattan, NY 10002",
    totalOrders: 15,
    totalSpent: 3456.89,
    joinedAt: "2024-11-10",
  },
  {
    name: "Chris Wilson",
    email: "chris@example.com",
    phone: "(555) 567-8901",
    address: "654 Maple Dr, Bronx, NY 10451",
    totalOrders: 3,
    totalSpent: 567.12,
    joinedAt: "2026-01-05",
  },
  {
    name: "Amanda Taylor",
    email: "amanda@example.com",
    phone: "(555) 678-9012",
    address: "987 Cedar Ln, Staten Island, NY 10301",
    totalOrders: 9,
    totalSpent: 1654.33,
    joinedAt: "2025-05-18",
  },
];

export const orderSeed = [
  {
    orderNumber: "ORD-001",
    customerEmail: "john@example.com",
    total: 459.99,
    status: "processing",
    items: 3,
    date: "2026-03-08",
  },
  {
    orderNumber: "ORD-002",
    customerEmail: "sarah@example.com",
    total: 899.99,
    status: "shipped",
    items: 2,
    date: "2026-03-07",
  },
  {
    orderNumber: "ORD-003",
    customerEmail: "mike@example.com",
    total: 234.5,
    status: "delivered",
    items: 1,
    date: "2026-03-06",
  },
  {
    orderNumber: "ORD-004",
    customerEmail: "emily@example.com",
    total: 678,
    status: "pending",
    items: 4,
    date: "2026-03-05",
  },
  {
    orderNumber: "ORD-005",
    customerEmail: "chris@example.com",
    total: 1234.99,
    status: "processing",
    items: 5,
    date: "2026-03-04",
  },
  {
    orderNumber: "ORD-006",
    customerEmail: "amanda@example.com",
    total: 345.75,
    status: "shipped",
    items: 2,
    date: "2026-03-03",
  },
];

export const quoteSeed = [
  {
    quoteNumber: "QT-001",
    name: "Robert Taylor",
    email: "robert@example.com",
    phone: "(555) 111-2222",
    productsCount: 4,
    total: 660,
    productsNeeded: "Faucets x2, Basins x2",
    status: "pending",
    date: "2026-03-09",
  },
  {
    quoteNumber: "QT-002",
    name: "Jennifer White",
    email: "jennifer@example.com",
    phone: "(555) 222-3333",
    productsCount: 7,
    total: 1285,
    productsNeeded: "Bulk sanitary package",
    status: "responded",
    date: "2026-03-08",
  },
  {
    quoteNumber: "QT-003",
    name: "David Miller",
    email: "david@example.com",
    phone: "(555) 333-4444",
    productsCount: 2,
    total: 490,
    productsNeeded: "Shower enclosure + shower head",
    status: "converted",
    date: "2026-03-07",
  },
  {
    quoteNumber: "QT-004",
    name: "Lisa Anderson",
    email: "lisa@example.com",
    phone: "(555) 444-5555",
    productsCount: 5,
    total: 975,
    productsNeeded: "Toilets and accessories package",
    status: "pending",
    date: "2026-03-06",
  },
  {
    quoteNumber: "QT-005",
    name: "James Garcia",
    email: "james@example.com",
    phone: "(555) 555-6666",
    productsCount: 3,
    total: 615,
    productsNeeded: "Basins x3",
    status: "responded",
    date: "2026-03-05",
  },
];

export const categorySeed = [
  { name: "Faucets", description: "Seasonal focus" },
  { name: "Toilets", description: "Seasonal focus" },
  { name: "Basins", description: "Seasonal focus" },
  { name: "Showers", description: "Seasonal focus" },
  { name: "Accessories", description: "Seasonal focus" },
];

export const brandSeed = [
  { name: "AquaFlow", description: "Supplier in good standing" },
  { name: "LuxeBath", description: "Supplier in good standing" },
  { name: "SaniPro", description: "Supplier in good standing" },
  { name: "TechSani", description: "Supplier in good standing" },
  { name: "CeraStyle", description: "Supplier in good standing" },
  { name: "Heritage", description: "Supplier in good standing" },
  { name: "RainDrop", description: "Supplier in good standing" },
  { name: "ThermoFlow", description: "Supplier in good standing" },
  { name: "GlassLux", description: "Supplier in good standing" },
  { name: "AccessPro", description: "Supplier in good standing" },
  { name: "MirrorTech", description: "Supplier in good standing" },
];
